[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# For SPA/client-side routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Cache control for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
